on: [push]
name: build
jobs:
  runhaskell:
    name: Hello World
    runs-on: ubuntu-latest # or macOS-latest, or windows-latest
    env:
      ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-haskell@v1.1
        with:
          ghc-version: '8.8.3' 
          cabal-version: '3.0.0.0'
      - run: runhaskell Hello.hs
