on: [push]
name: build
jobs:
  runhaskell:
    name: Build and deploy
    runs-on: ubuntu-latest # or macOS-latest, or windows-latest
    env:
      ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
      GHC_VERSION: '8.8.3'
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-haskell@v1.1
        with:
          ghc-version: ${{env.GHC_VERSION}} 
          enable-stack: true
          stack-version: 'latest'
      - uses: cachix/install-nix-action@v12
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - run: stack run
